default: &default
  adapter: postgresql
  encoding: unicode
  database: photoapplication
  pool: 5

development:
  <<: *default

test:
  <<: *default

testing:
  <<: *default

production:
  <<: *default